### PR TITLE
fields_for_collection: Fix name attribute

### LINKED ISSUE #111: Select and textarea helpers don't compute the correct name attribute
Looking at [this](https://github.com/hanami/helpers/issues/110#issue-256972284) and [this](https://github.com/hanami/helpers/pull/107#issuecomment-326688700):

When inside a `fields_for_collection` block, indexes aren't stripped from `select` and `textearea` name attributes.

### LINKED ISSUE #116: Some helper methods produce wrong `name` attributes when called in `fields_for_collection` block
Some helper methods return wrong `name` attributes when called from within a `fields_for_collection` block. Here's a minimal example:

```erb
<%=
  sub_entity1 = OpenStruct.new(key1: 'a1', key2: true, other_key1: 'c1', other_key2: 'd1', id: 1)
  sub_entity2 = OpenStruct.new(key1: 'a2', key2: true, other_key1: 'c2', other_key2: 'd2', id: 2)

  thing = OpenStruct.new(sub_entities: [sub_entity1, sub_entity2])

  form_for :thing, '/books/1', method: :put, values: {thing: thing} do
    fields_for_collection :sub_entities do
      hidden_field :id
      text_area :key1
      check_box :key2
      text_area :other_key1
      text_field :other_key1
      select :other_key2, [['d1', 'd1'], ['d2', 'd2']]
    end
    submit 'Save'
  end
%>
```

This produces:
```html
<form action="/books/1" method="POST" accept-charset="utf-8" id="thing-form">
  <input type="hidden" name="_method" value="PUT">
  <input type="hidden" name="thing[sub_entities][][id]" id="thing-sub-entities-0-id" value="1">
  <textarea type="textarea" name="thing[sub_entities][0][key1]" id="thing-sub-entities-0-key1" value="a1">a1</textarea>
  <input type="hidden" name="thing[sub_entities][0][key2]" value="0">
  <input type="checkbox" name="thing[sub_entities][0][key2]" id="thing-sub-entities-0-key2" value="1" checked="checked">
  <textarea type="textarea" name="thing[sub_entities][0][other_key1]" id="thing-sub-entities-0-other-key1" value="c1">c1</textarea>
  <input type="text" name="thing[sub_entities][][other_key1]" id="thing-sub-entities-0-other-key1" value="c1">
  <select name="thing[sub_entities][0][other_key2]" id="thing-sub-entities-0-other-key2">
    <option value="d1" selected="selected">d1</option>
    <option value="d2">d2</option>
  </select>
  <input type="hidden" name="thing[sub_entities][][id]" id="thing-sub-entities-1-id" value="2">
  <textarea type="textarea" name="thing[sub_entities][1][key1]" id="thing-sub-entities-1-key1" value="a2">a2</textarea>
  <input type="hidden" name="thing[sub_entities][1][key2]" value="0">
  <input type="checkbox" name="thing[sub_entities][1][key2]" id="thing-sub-entities-1-key2" value="1" checked="checked">
  <textarea type="textarea" name="thing[sub_entities][1][other_key1]" id="thing-sub-entities-1-other-key1" value="c2">c2</textarea>
  <input type="text" name="thing[sub_entities][][other_key1]" id="thing-sub-entities-1-other-key1" value="c2">
  <select name="thing[sub_entities][1][other_key2]" id="thing-sub-entities-1-other-key2">
    <option value="d1">d1</option>
    <option value="d2" selected="selected">d2</option>
  </select>
  <button type="submit">Save</button>
</form>
```

Note how the `name` attribute for the `hidden_field` and the `text_field` are ok (e.g. `thing[sub_entities][][id]`). But they're wrong for at least `text_area`, `check_box` and `select` (haven't looked at the others): `thing[sub_entities][1][key1]`.

Apparently `_attributes` which calls `_displayed_input_name` does not get called for all helpers.

### PR DESCRIPTION
**Pull request by AlfonsoUceda**
This PR fixes #116 and fixes #111

@nerdinand can you take a look please? Thanks ;)

After merge, please cherry pick to master.

### CODE REVIEW

**Comment by nerdinand** [comment]
Looks good to me! 👍

**Comment by AlfonsoUceda** [comment]
@nerdinand one more thing, can you check if it repairs #117? I'll test it later if I can.

**Comment by nerdinand** [comment]
@AlfonsoUceda No, this does not fix #117, I just checked.

**Review by jodosha — APPROVED** [review]
@AlfonsoUceda you're my hero! 💯

**Pull request merged**
