### PR TITLE
Form helper: disable option for select prompt

### PR DESCRIPTION
**Pull request by TiteiKo**
Prompt option shouldn't be enabled in generated select

### CODE REVIEW

**Comment by TiteiKo** [comment]
Please don't merge, I want to add the selected attribute to the prompt if there's nothing selected

**Comment by cllns** [comment]
👍 good find and good work!

**Comment by jodosha** [comment]
@TiteiKo Any progress on this enhancement? Would you like to see it in 1.1.0?

**Comment by AlfonsoUceda** [comment]
ping @TiteiKo

**Comment by AlfonsoUceda** [comment]
Folks, after checking this PR in deep I'm against this change, disabled attribute shouldn't be set by default for prompt option, the use should do this.

For example, usually we use prompt for default selected option and we select some valid option, after some time we want to disable that change, selecting again our prompt option.

@jodosha @TiteiKo I'm going to close it, if you think I'm wrong, please comment this PR.

**Pull request closed without merging**
