### PR TITLE
Add failing spec to reproduce #114

### PR DESCRIPTION
**Pull request by nerdinand**

### CODE REVIEW

**Comment by AlfonsoUceda** [comment]
Thanks @nerdinand, if you want to explore the solution go ahead, if not, I'll try to take a look ;)

**Comment by nerdinand** [comment]
@AlfonsoUceda I tried to figure it out but reproducing it in a test is all I was capable of. I think I don't know the code well enough.

**Comment by jodosha** [comment]
@nerdinand My understanding of #114 was that only JRuby was causing issues for you. From what I can tell from the CI build of this PR, also MRI fails.

Do you know why?

**Comment by nerdinand** [comment]
@jodosha I don't know why, but I noticed it too, see: https://github.com/hanami/helpers/issues/114#issuecomment-381574667

Looks like the two things are unrelated, but I'd still consider them bugs if you agree with the premise of the test...

**Comment by jodosha** [comment]
@nerdinand Maybe they are related..
If I replace `text` with another `radio_button`, I get an infinite loop.

Do you have time to look at this? Please let me know. Thanks.

**Comment by nerdinand** [comment]
@jodosha i currently don't have any time to investigate...

**Comment by jodosha** [comment]
Closed as stale conversation.

**Pull request closed without merging**
