### PR TITLE
Update form elements

### PR DESCRIPTION
**Pull request by jodosha**
This PR introduces new form helpers:

  * `image_button` (`<input type="image">`)
  * `range_field` (`<input type="range">`)
  * `search_field` (`<input type="search">`)
  * `url_field` (`<input type="url">`)
  * `tel_field` (`<input type="tel">`)

### CODE REVIEW

**Comment by jodosha** [comment]
Probably tweaking YARD in some way, but I'm not sure if it's worth the trouble.

**Comment by jodosha** [comment]
@davydovanton @mereghost This is now ready to be reviewed. Can you please have a look? Thanks! 👍

**Comment by jodosha** [comment]
@davydovanton WDYM?

**Comment by davydovanton** [comment]
I mean that some helpers are rarely used but we have code for this and we need to support this code too. That's why I have this skeptic question.

**Comment by jodosha** [comment]
@davydovanton I see. Well, it isn't too much burden to maintain these one-line functions IMO 😉 . We also encourage and support HTML5 specific inputs, that act as validator on the browser side.

**Pull request merged**
