### PR TITLE
Fix FormBuilder populating form values

### LINKED ISSUE #84: FormBuilder not filling the input fields
Given a form with passed values: 

```ruby
<%= form_for :entity, routes.entities_path, values: { entity: Entity.new(field: 1) }
text_field :field
end %>
```

The text_field will not be filled at all. I tracked the problem down to the `Values#_get_from_values` [message](https://github.com/hanami/helpers/blob/master/lib/hanami/helpers/form_helper/values.rb#L44).

Now that entities are implicitly serializable to hashes (as they respond to `to_hash`), they become hashes during the `Values#initialize` and therefore the `public_send(k)` will always return `nil`.

### PR DESCRIPTION
**Pull request by myabc**
Apparent regression in Hanami 0.9.x series.

Fixes #84

### CODE REVIEW

**Comment by myabc** [comment]
@jodosha this appears to me to be the simplest solution. I do not really see the value in teaching `Values#_get_from_values` to understand hashes.

/ @mereghost

**Comment by mereghost** [comment]
Yep this could solve the problem, but I'm not sure it's the way everything else is going. Even `Interactor`s are [returning simple hashes](https://github.com/hanami/utils/blob/master/lib/hanami/interactor.rb#L136) since the changes on `Model` to become frozen and implicit convertible to a hash. That would solve the issue with the form builder but leave the whole thing a bit inconsistent.

OTOH, if the forms only operated on Hash-like objects (Params & Utils::Hash) the internals could be simplified and testing would become simpler too.

**Comment by myabc** [comment]
@mereghost Alternative solution based on your feedback here: https://github.com/hanami/helpers/pull/87

> OTOH, if the forms only operated on Hash-like objects (Params & Utils::Hash) the internals could be simplified and testing would become simpler too.

**Comment by mereghost** [comment]
At the same time, the time to break compatibility is right now, before we move to 1.0.

**Comment by myabc** [comment]
Closing in favour of #87

**Pull request closed without merging**
